= JIRA ticket
:jbake-date: 2018-12-10
:jbake-type: page
:jbake-status: published


In order to keep track of all the tasks concerning TomEE there should be a ticket in the link:https://issues.apache.org/jira/browse/TOMEE[TomEE JIRA] for each work item. +
Before you can create tickets, you have to link:https://issues.apache.org/jira/secure/Signup!default.jspa[sign up] for an account.

== No task without a ticket
Before you start working on a task you should ensure that there is a ticket for your task. +
Browse JIRA and use the search function to find out if there is already a ticket for what you want to pick up.
If not, create a new one.

== Avoiding conflicts and wasted effort
If a ticket already exists and is assigned to someone you should not start working on this task. +
If you want to help, contact the assigned person using the mailing list or write a comment in the JIRA ticket.

== Pick up a task
To inform others that you are working on a task, the corresponding ticket in JIRA should be assigned to you. +
If you don't have permission to assign tickets (there is no edit sign behind the Field "Assignee"), just ask on the developers mailing list.

(xref:workflow.adoc[back to Contribution workflow])
