= Process task
:jbake-date: 2018-12-10
:jbake-type: page
:jbake-status: published


== Fork project repository
You can work on the xref:../sources.adoc[source code of TomEE] using GitHub.
If you don't have a GitHub account, you can link:https://GitHub.com/[sign up here].
To create your own working area, go to the project link:https://github.com/apache/tomee[TomEE on GitHub] and click on the link "Fork".
A forked repository will be created for your account and you will be redirected to it.

== One branch for each ticket
Although you can work on the master branch it is advisable to create a new branch for each ticket you start to work on - even if it's only one.
Use the JIRA id and title as name of the branch. 

== Get help
If you need help or want to have feedback for your ideas write to the developes mailing list.

== Hands on
Work on the code. Use local commit as often as you want.
Use push (to your own forked repository) as often as you like.
Consider the xref:contribution-tips.adoc[contribution tips].
If a task is to hard to get it done: no problem. Just ask for help.
If you want to cancel working on a task, don't forget to unassign the JIRA ticket!

== Comments in JIRA
Use comments for the JIRA ticket to document your work.

(xref:workflow.adoc[back to Contribution workflow])
