= Community
:jbake-date: 2016-03-16
:jbake-type: page
:jbake-status: published

=== The Source Code

Want to grab TomEE source code and hack it? Nothing simpler, just go link:sources.html[there].

=== Contributors

You can see our wall of fame on: link:contributors.html[TomEE Wall Of Fame].

=== Social Media: cause contributing is not only about coding

Facebook, Twitter, Google+: if that speaks to you just follow this link:social.html[TomEE on Social Media].

=== Support

For more information about available support for TomEE please have a look on link:../security/support.html[Support] page.

=== Contribute to This Website

This website is a simple link:http://jbake.org/[JBake] project you can find at https://github.com/apache/tomee-site-generator.git.

To submit a change do the following:

- Create a ticket on http://issues.apache.org/jira/browse/TOMEE

- Open a PR with the ticket number e.g `TOMEE-1000 - Ticket Description`

A committer will review it and redeploy the website using Apache CMS.

Building the website is mainly about running `mvn compile`, note you can use `JBake` main to develop.
Publishing the website is about running `mvn pre-site` - needs to be a TomEE committer.
