= Community
:jbake-date: 2016-03-16
:jbake-type: page
:jbake-status: published

=== Source Code

Want to grab TomEE source code and hack it? Nothing simpler, just go link:sources.html[there].

=== Contributors

You can see our wall of fame on: link:contributors.html[TomEE Wall Of Fame].

=== Social Media: cause contributing is not only about coding

Facebook, Twitter, Google+: if that speaks to you just follow this link:social.html[TomEE on Social Media].

=== Support

For more information about available support for TomEE please have a look on link:../security/support.html[Support] page.

=== Contribute to this website

This website is a simple JBake project you can find at https://git-wip-us.apache.org/repos/asf/tomee-site-generator.git.

For more information please have a look to
https://git-wip-us.apache.org/repos/asf?p=tomee-site-generator.git;a=blob;f=README.adoc;h=0fefd33b398fca05854ce46f3c5ebcb4a5ef107a;hb=refs/heads/master
and http://jbake.org/.

To submit a change create a ticket on http://issues.apache.org/jira/browse/TOMEE and attach a diff
with the content. Then a committer will review it and redeploy the website using Apache CMS.

Building the website is mainly about running `mvn compile`, note you can use `JBake` main to develop.
Publishing the website is about running `mvn pre-site` - needs to be a TomEE committer.
