= Community
:jbake-date: 2016-03-16
:jbake-type: page
:jbake-status: published

=== In code veritas est

Want to grab TomEE source code and hack it? Nothing simpler, just go link:sources.html[there].

=== Contributors

You can see our wall of fame on: link:contributors.html[TomEE Wall Of Fame].

=== Social Media: cause contributing is not only about coding

Facebook, Twitter, Google+: if that speaks to you just follow this link:social.html[TomEE on Social Media].

=== Support

For more information about available support for TomEE please have a look on link:../security/support.html[Support] page.

=== Contribute the this website

This website is a simple JBake project you can find at http://svn.apache.org/repos/asf/tomee/site/trunk/generators/site-tomee-ng/.

For more information please have a look to http://svn.apache.org/repos/asf/tomee/site/trunk/generators/site-tomee-ng/README.adoc
and http://jbake.org/.

To submit a change create a ticket on http://issues.apache.org/jira/browse/TOMEE and attach a diff
with the content. Then a committer will review it and redeploy the website using Apache CMS.
