= Design - Container
:jbake-type: page
:jbake-status: published

== Container

Sub-component of xref:design.adoc[OpenEJB]

== Definition

An Enterprise JavaBeans container enforce the container-bean contract for an EJB 1.1, 2.0, 2.1 or 3.0 bean type.
Containers for custom container-bean contracts can also be created.

== Also Known As

* Container Provider

== Responsibilities

* Adopt the OpenEJB architecture
* Use the Transaction Manager assigned to the container system to assist in handling transactions
* Use the Security Manager assigned to the container system to assist in enforcing security and privileges
* Implement the org.apache.openejb.Container interface

== Related Classes

* org.apache.openejb.Container

== Implementations

* xref:design-stateful-sessionbean-container.adoc[Stateful SessionBean Container]
* xref:design-stateless-sessionbean-container.adoc[Stateless SessionBean Container]
* xref:design-bmp-entitybean-container.adoc[BMP EntityBean Container]
* xref:design-cmp-entitybean-container.adoc[CMP EntityBean Container]
